version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mon_user
      POSTGRES_PASSWORD: mon_password
      POSTGRES_DB: ma_base
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:
